[package]
name = "client"
version = "0.1.0"
edition = "2021"
rust-version = "1.63"

[dependencies]
reqwest = "0.12.5"
tokio = { version = "1.38.0", features = ["full"] }
prost = "0.11.6"
protos = { path = "../protos" }
