[workspace]
members = [
    "ldk-node-hack-server", 
    "common", 
    "cli",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.76"

[workspace.dependencies]
tokio = { version = "1.38.0", features = ["full"] }
prost = "0.11.6"

