[package]
name = "ldk-node-hack-server"
version = "0.1.0"
edition = "2021"

[dependencies]
ldk-node = { git = "https://github.com/tnull/ldk-node-hack.git", branch = "main" }
tokio = { version = "1.38.0", features = ["full"] }
