[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
common = { version = "0.1.0", path = "../common" }
tonic = "0.11.0"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
