[package]
name = "cli"
version.workspace = true
edition.workspace = true

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
common = { version = "0.1.0", path = "../common" }
tokio = { workspace = true }