[package]
name = "common"
version.workspace = true
edition.workspace = true

[dependencies]
reqwest = "0.12.5"
tonic = "0.11.0"
prost = { workspace = true }
tokio = { workspace = true }

[build-dependencies]
tonic-build = "0.11.0"
prost-build = "0.12.6"
